{
  "openapi": "3.1.0",
  "info": {
    "title": "go_ws_sh",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/tokens": {
      "post": {
        "summary": "创建令牌",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "POST",
            "required": false,
            "example": "POST",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "token": {
                    "$ref": "#/components/schemas/token"
                  }
                },
                "required": [
                  "authorization",
                  "token"
                ],
                "x-apifox-orders": [
                  "authorization",
                  "token"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "59",
                  "username": "通鹏",
                  "token": "dolore Lorem ut",
                  "password": "u1H84FL1dygv6H7",
                  "type": "do veniam consectetur aliqua amet"
                },
                "token": {
                  "description": "联太为养复近造只手适。展志斯。子世年存种行成车交。决么林快效不原回团。老度史半在命质。术者照会接。是导响飞产提论我育定。",
                  "username": "束艳",
                  "identifer": "59",
                  "token": "Excepteur commodo enim ullamco ex"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "$ref": "#/components/schemas/token"
                    },
                    "username": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message",
                    "token",
                    "username"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "token",
                    "username"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "laborum id",
                  "token": {
                    "description": "常应儿到统型整就这。本务记子权方。计选增酸单带断。况样南起据报题象门。然法深六认委两量。山事体。交满据至被了。",
                    "username": "蒲梓豪",
                    "identifer": "68",
                    "token": "laborum nulla nostrud"
                  },
                  "username": "空紫林"
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274376204-run"
      },
      "put": {
        "summary": "修改令牌",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "object",
                    "properties": {
                      "identifer": {
                        "type": "string",
                        "title": "",
                        "description": ""
                      },
                      "description": {
                        "type": "string",
                        "title": "",
                        "description": ""
                      }
                    },
                    "required": [
                      "identifer",
                      "description"
                    ],
                    "x-apifox-orders": [
                      "identifer",
                      "description"
                    ],
                    "x-apifox-ignore-properties": []
                  },
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  }
                },
                "required": [
                  "token",
                  "authorization"
                ],
                "x-apifox-orders": [
                  "token",
                  "authorization"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "token": {
                  "identifer": "37",
                  "description": "细矿义。合认便情用南别法重同。解思周。把话老权道选带全百。院条实际展。提确备最广具术去包制。果流口布正大。温你任人然算。"
                },
                "authorization": {
                  "identifer": "2",
                  "username": "表志明",
                  "token": "id sit",
                  "password": "rizLm0jfLMpJoCE",
                  "type": "velit Lorem voluptate in"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "token": {
                      "$ref": "#/components/schemas/token"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "token"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "token"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "sed deserunt ut",
                  "username": "及志国",
                  "token": {
                    "description": "物除支斗保了研况。合和世米。教素华老代石究。",
                    "username": "冀梓豪",
                    "identifer": "44"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274961165-run"
      },
      "delete": {
        "summary": "删除令牌",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "$ref": "#/components/schemas/token"
                  },
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  }
                },
                "required": [
                  "token",
                  "authorization"
                ],
                "x-apifox-orders": [
                  "token",
                  "authorization"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "token": {
                  "description": "也难各况老须山办何线。酸线给名。好东声间候下制备。受你质白东本处次较命。示难这名组合。专市该资。",
                  "username": "始国强",
                  "identifer": "59",
                  "token": "in ipsum"
                },
                "authorization": {
                  "identifer": "98",
                  "username": "斋国珍",
                  "token": "reprehenderit sit id",
                  "password": "hkjNbMjFHCBrkbx",
                  "type": "sunt officia nulla ut ut"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "token": {
                      "$ref": "#/components/schemas/token"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "token"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "token"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "tempor",
                  "username": "公伟",
                  "token": {
                    "description": "边太支消二水作写山。参去类。据素队族取只维证除教。清些建石万种单常。有地开斗无点查号。美报行何。有议手已达。",
                    "username": "邶晨阳",
                    "identifer": "84",
                    "token": "fugiat deserunt non ea",
                    "updated_at": "2025-01-26",
                    "created_at": "2025-01-19 09:31:37"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274376376-run"
      },
      "get": {
        "summary": "显示令牌",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "GET",
            "required": true,
            "example": "GET",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "token": {
                    "type": "object",
                    "properties": {
                      "identifer": {
                        "type": "string",
                        "title": "",
                        "description": ""
                      }
                    },
                    "x-apifox-orders": [
                      "identifer"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "required": [
                  "authorization"
                ],
                "x-apifox-orders": [
                  "authorization",
                  "token"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifier": "46",
                  "username": "柳家明",
                  "token": "dolor laborum in",
                  "password": "UxJxy1iIaZYubxt",
                  "type": "voluptate id"
                },
                "token": {
                  "identifer": "9"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    },
                    "tokens": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/token"
                      }
                    }
                  },
                  "required": [
                    "message",
                    "tokens",
                    "username"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "tokens"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "aliquip magna laborum",
                  "username": "市熙成",
                  "tokens": [
                    {
                      "description": "条物先义价级地后。中门队种导力表。只矿处。",
                      "username": "钭苡沫",
                      "identifer": "14",
                      "token": "sint magna id eiusmod aliqua",
                      "updated_at": "2025-10-04",
                      "created_at": "2026-02-08 12:55:32"
                    }
                  ]
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274369260-run"
      }
    },
    "/credentials": {
      "put": {
        "summary": "修改密码",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "credential": {
                    "$ref": "#/components/schemas/credential"
                  }
                },
                "x-apifox-orders": [
                  "authorization",
                  "credential"
                ],
                "required": [
                  "authorization",
                  "credential"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "11",
                  "username": "京万佳",
                  "token": "nisi proident",
                  "password": "HQHsYZOyvSkcizB",
                  "type": "velit"
                },
                "credential": {
                  "username": "明苡沫",
                  "password": "ZpWWRl4fkBCmcZG"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "credential": {
                      "$ref": "#/components/schemas/credential"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "credential"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "credential"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "id ut proident Ut",
                  "username": "隗秀珍",
                  "credential": {
                    "username": "羊国华",
                    "password": "GRTGxa6qmWPT8y5"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274376804-run"
      },
      "delete": {
        "summary": "删除用户",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "credential": {
                    "$ref": "#/components/schemas/credential"
                  }
                },
                "x-apifox-orders": [
                  "authorization",
                  "credential"
                ],
                "required": [
                  "authorization",
                  "credential"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "29",
                  "username": "阎晨",
                  "token": "eu",
                  "password": "Ax1RzKvcJA7FQZj",
                  "type": "minim fugiat"
                },
                "credential": {
                  "username": "衡刚",
                  "password": "xvJw7L2YnmNOjag"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "credential": {
                      "$ref": "#/components/schemas/credential"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "credential"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "credential"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "dolore",
                  "username": "百丽",
                  "credential": {
                    "username": "恭玲",
                    "password": "viPAfChquGKeQ6K"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274957742-run"
      },
      "get": {
        "summary": "显示用户",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "GET",
            "required": true,
            "example": "GET",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "credential": {
                    "type": "object",
                    "properties": {
                      "username": {
                        "type": "string",
                        "title": "",
                        "description": ""
                      }
                    },
                    "x-apifox-orders": [
                      "username"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "required": [
                  "authorization"
                ],
                "x-apifox-orders": [
                  "authorization",
                  "credential"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifier": "67",
                  "username": "涂治涛",
                  "token": "nostrud laboris",
                  "password": "IC1C7DGgBSf3sHE",
                  "type": "ea"
                },
                "credential": {
                  "username": "益乙萍"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "credentials": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/credential"
                      },
                      "title": "",
                      "description": ""
                    },
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    }
                  },
                  "required": [
                    "credentials",
                    "message",
                    "username"
                  ],
                  "x-apifox-orders": [
                    "credentials",
                    "message",
                    "username"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "credentials": [
                    {
                      "username": "老英",
                      "password": "EAr9I5PnZ6ioOdk",
                      "updated_at": "2024-08-11",
                      "created_at": "2025-12-10 13:17:08"
                    }
                  ],
                  "message": "cillum ea laboris do",
                  "username": "荣佳琪"
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274956715-run"
      },
      "post": {
        "summary": "创建用户",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "POST",
            "required": false,
            "example": "POST",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "credential": {
                    "$ref": "#/components/schemas/credential"
                  }
                },
                "x-apifox-orders": [
                  "authorization",
                  "credential"
                ],
                "required": [
                  "authorization",
                  "credential"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "8",
                  "username": "苌雨桐",
                  "token": "dolor incididunt pariatur",
                  "password": "SmuJxITZXdNYS__",
                  "type": "non"
                },
                "credential": {
                  "username": "僪语桐",
                  "password": "zXWuNkm6lQJABvj"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "credential": {
                      "$ref": "#/components/schemas/credential"
                    },
                    "message": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    },
                    "username": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    }
                  },
                  "x-apifox-orders": [
                    "credential",
                    "message",
                    "username"
                  ],
                  "required": [
                    "credential",
                    "message",
                    "username"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "credential": {
                    "username": "窦宇航",
                    "password": "l4toCzQ3SzXMK2Q"
                  },
                  "message": "proident irure commodo ipsum laborum",
                  "username": "本政君"
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274973430-run"
      }
    },
    "/sessions": {
      "put": {
        "summary": "修改会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "session": {
                    "$ref": "#/components/schemas/session"
                  }
                },
                "required": [
                  "authorization",
                  "session"
                ],
                "x-apifox-orders": [
                  "authorization",
                  "session"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "9",
                  "username": "郦桂兰",
                  "token": "ad nisi fugiat eu nulla",
                  "password": "vhkN6hb1ZubYJw5",
                  "type": "consectetur enim"
                },
                "session": {
                  "name": "盈雯静",
                  "args": [
                    "dolor Lorem eu aliquip",
                    "fugiat dolor",
                    "irure aute commodo magna"
                  ],
                  "dir": "laboris elit",
                  "cmd": "laboris sunt sint"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "session": {
                      "$ref": "#/components/schemas/session"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "elit eu nostrud",
                  "username": "镇馨羽",
                  "session": {
                    "name": "斯娟",
                    "cmd": "culpa occaecat est",
                    "dir": "amet adipisicing dolor non",
                    "args": [
                      "adipisicing",
                      "sed do Lorem Duis"
                    ]
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274959038-run"
      },
      "delete": {
        "summary": "删除会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "session": {
                    "$ref": "#/components/schemas/session"
                  },
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  }
                },
                "required": [
                  "session",
                  "authorization"
                ],
                "x-apifox-orders": [
                  "session",
                  "authorization"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "session": {
                  "name": "全丽芳",
                  "args": [
                    "ullamco culpa",
                    "amet aliqua est",
                    "quis Ut aliqua ex"
                  ],
                  "dir": "laboris",
                  "cmd": "amet incididunt do culpa labore"
                },
                "authorization": {
                  "identifer": "31",
                  "username": "龙秀英",
                  "token": "nulla dolore officia",
                  "password": "EhQLnzz1kTcnyz6",
                  "type": "pariatur aute labore enim"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "session": {
                      "$ref": "#/components/schemas/session"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "in",
                  "username": "容诗雨",
                  "session": {
                    "name": "繁国英",
                    "args": [
                      "eiusmod anim sit",
                      "nulla exercitation aliqua culpa",
                      "in ad velit cupidatat"
                    ],
                    "dir": "dolor",
                    "cmd": "exercitation"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274974610-run"
      },
      "copy": {
        "summary": "复制会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "COPY",
            "required": true,
            "example": "COPY",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "session": {
                    "$ref": "#/components/schemas/session"
                  },
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "destination": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "名称"
                      }
                    },
                    "x-apifox-orders": [
                      "name"
                    ],
                    "required": [
                      "name"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "required": [
                  "session",
                  "authorization",
                  "destination"
                ],
                "x-apifox-orders": [
                  "session",
                  "authorization",
                  "destination"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "session": {
                  "name": "霜国栋",
                  "args": [
                    "esse eu",
                    "fugiat sit Lorem est"
                  ],
                  "dir": "nostrud amet consequat",
                  "cmd": "esse dolore Duis do sunt",
                  "created_at": "2024-10-19 06:27:58",
                  "updated_at": "2024-04-10"
                },
                "authorization": {
                  "identifier": "9",
                  "username": "睢勇",
                  "token": "enim nostrud ad deserunt anim",
                  "password": "g2AwDm9_yC_Zd35",
                  "type": "nulla officia sed"
                },
                "destination": {
                  "name": "越语桐"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "session": {
                      "$ref": "#/components/schemas/session"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "in",
                  "username": "容诗雨",
                  "session": {
                    "name": "繁国英",
                    "args": [
                      "eiusmod anim sit",
                      "nulla exercitation aliqua culpa",
                      "in ad velit cupidatat"
                    ],
                    "dir": "dolor",
                    "cmd": "exercitation"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-280558903-run"
      },
      "move": {
        "summary": "移动会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "MOVE",
            "required": true,
            "example": "MOVE",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "session": {
                    "$ref": "#/components/schemas/session"
                  },
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "destination": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      }
                    },
                    "x-apifox-orders": [
                      "name"
                    ],
                    "required": [
                      "name"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "required": [
                  "session",
                  "authorization",
                  "destination"
                ],
                "x-apifox-orders": [
                  "session",
                  "authorization",
                  "destination"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "session": {
                  "name": "仲孙雅鑫",
                  "args": [
                    "eiusmod Duis ad laboris",
                    "officia"
                  ],
                  "dir": "nostrud irure ad laboris velit",
                  "cmd": "culpa ex elit",
                  "created_at": "2025-08-27 15:09:03",
                  "updated_at": "2026-02-01"
                },
                "authorization": {
                  "identifier": "80",
                  "username": "麻国琴",
                  "token": "aute eu",
                  "password": "Fsi41VK0DrQ4W_H",
                  "type": "culpa"
                },
                "destination": {
                  "name": "改国英"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "session": {
                      "$ref": "#/components/schemas/session"
                    }
                  },
                  "required": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-orders": [
                    "message",
                    "username",
                    "session"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "message": "in",
                  "username": "容诗雨",
                  "session": {
                    "name": "繁国英",
                    "args": [
                      "eiusmod anim sit",
                      "nulla exercitation aliqua culpa",
                      "in ad velit cupidatat"
                    ],
                    "dir": "dolor",
                    "cmd": "exercitation"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-280558985-run"
      },
      "get": {
        "summary": "显示会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "GET",
            "required": true,
            "example": "GET",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "session": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      }
                    },
                    "x-apifox-orders": [
                      "name"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "x-apifox-orders": [
                  "authorization",
                  "session"
                ],
                "required": [
                  "authorization"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifier": "9",
                  "username": "恭政君",
                  "token": "mollit ea Lorem reprehenderit",
                  "password": "68f9y_RPl7lzH2W",
                  "type": "est deserunt dolore amet laborum"
                },
                "session": {
                  "name": "弥诗雨"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "sessions": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/session"
                      }
                    },
                    "message": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "sessions",
                    "message",
                    "username"
                  ],
                  "x-apifox-orders": [
                    "sessions",
                    "message",
                    "username"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "sessions": [
                    {
                      "name": "余桂英",
                      "args": [
                        "Ut"
                      ],
                      "dir": "enim voluptate occaecat do ipsum",
                      "cmd": "Lorem aliquip",
                      "created_at": "2025-09-08 16:23:31",
                      "updated_at": "2025-09-17"
                    }
                  ],
                  "message": "amet ut sunt",
                  "username": "终玉梅"
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-250659538-run"
      },
      "post": {
        "summary": "创建会话",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "x-HTTP-method-override",
            "in": "header",
            "description": "POST",
            "required": false,
            "example": "POST",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "authorization": {
                    "$ref": "#/components/schemas/authorization"
                  },
                  "session": {
                    "$ref": "#/components/schemas/session"
                  }
                },
                "x-apifox-orders": [
                  "authorization",
                  "session"
                ],
                "required": [
                  "authorization",
                  "session"
                ],
                "x-apifox-ignore-properties": []
              },
              "example": {
                "authorization": {
                  "identifer": "90",
                  "username": "郁勇",
                  "token": "do eiusmod",
                  "password": "mXpnuFnILrjhuGJ",
                  "type": "dolore nulla Ut ut proident"
                },
                "session": {
                  "name": "祈雨欣",
                  "args": [
                    "proident",
                    "cillum esse dolore ut amet",
                    "laborum sint culpa"
                  ],
                  "dir": "fugiat dolore ut reprehenderit sed",
                  "cmd": "anim"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "session": {
                      "$ref": "#/components/schemas/token"
                    },
                    "message": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    },
                    "username": {
                      "type": "string",
                      "title": "",
                      "description": ""
                    }
                  },
                  "x-apifox-orders": [
                    "session",
                    "message",
                    "username"
                  ],
                  "required": [
                    "session",
                    "message",
                    "username"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "session": {
                    "description": "白住利适广的确压断院。一三就具出管。育程成及她不治都带只。科变利前。被接业把五。形备委都门立理场色资。志立候头消改流需报。条万业前风。",
                    "username": "星国平",
                    "identifer": "42",
                    "token": "Excepteur dolore sit amet"
                  },
                  "message": "do",
                  "username": "夔蒙"
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/5707825/apis/api-274971279-run"
      }
    }
  },
  "components": {
    "schemas": {
      "authorization": {
        "type": "object",
        "properties": {
          "identifier": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "username": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "token": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "password": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "type": {
            "type": "string",
            "title": "",
            "description": ""
          }
        },
        "x-apifox-orders": [
          "identifier",
          "username",
          "token",
          "password",
          "type"
        ],
        "required": [
          "identifier",
          "username",
          "token",
          "password",
          "type"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      },
      "token": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "username": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "identifier": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "token": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "created_at": {
            "type": "string",
            "title": "",
            "description": ""
          }
        },
        "x-apifox-orders": [
          "description",
          "username",
          "identifier",
          "token",
          "updated_at",
          "created_at"
        ],
        "required": [
          "description",
          "username",
          "identifier",
          "token",
          "updated_at",
          "created_at"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      },
      "session": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "args": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "dir": {
            "type": "string"
          },
          "cmd": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "title": "",
            "description": ""
          }
        },
        "x-apifox-orders": [
          "name",
          "args",
          "dir",
          "cmd",
          "created_at",
          "updated_at"
        ],
        "required": [
          "created_at",
          "updated_at"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      },
      "credential": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string",
            "title": "",
            "description": ""
          },
          "updated_at": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        },
        "x-apifox-orders": [
          "username",
          "password",
          "updated_at",
          "created_at"
        ],
        "required": [
          "username",
          "password",
          "updated_at",
          "created_at"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      }
    },
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}